import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import profilePic from '../../public/images/profile/developer-pic-2.png'
import AnimatedText from '@/components/AnimatedText'
import Link from 'next/link'
import { LinkArrow } from '@/components/Icons'
import CircleText from '@/components/CircleText'
import lightbulb from '../../public/images/svgs/akthar1.svg'

export default function Home() {
  return (
    <>
      <Head>
        <title>Akthar Aki</title>
        <meta name="description" content="Generated by Akthar Aki" />

      </Head>
      <main className='flex items-center text-dark w-full min-h-screen dark:text-light'>
        <Layout className='pt-0 md:pt-16 sm:p-8'>
          <div className='flex items-center justify-between w-full lg:flex-col'>
            <div className='w-1/2 md:w-full'>
              <Image src={profilePic} alt='' className='w-full h-auto lg:hidden md:inline-block md:w-full' 
              priority
              sizes='(max-width: 768px) 100vw,
              (max-width: 1200px) 50vw, 50vw'
              />
            </div>
            <div className='w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center'>
              <AnimatedText text='Hello Guys!, Welcome to DDC_Code And Design.' className='!text-6xl !text-left
              xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl'/>
              <p className='my-4 text-base font-medium md:text-sm sm:text-xs'>
              As a skilled front-end developer, I am dedicated to turning ideas into innovative web applications. 
              Explore my latest projects and articles, showcasing my expertise in React.js and web development.
              </p>
              <div className='flex items-center self-start mt-2 lg:self-center'>
                <Link href='./Makarim Akthar_CV.pdf' target={'_blank'}
                className='flex items-center bg-dark text-light p-2.5 px-6
                rounded-lg text-lg font-semibold hover:bg-light hover:text-dark
                border-2 border-solid border-transparent hover:border-dark
                 dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light
                 hover:dark:border-light'
                download={true}
                >
                Resume <LinkArrow className={'w-6 ml-1'} />
                </Link>
                <Link href='aabith619@gmail.com' target={'_blank'}
                className='ml-4 text-lg font-medium capitalize text-dark underline dark:text-light'
                >Contact</Link>
              </div>
            </div>
          </div>
        </Layout>

        <CircleText />
        <div className=' absolute right-8 bottom-8 inline-block w-36 dark:fill-light md:w-60 md:pb-60 sm:w-48 xs:w-36 xs:pb-52'>
          <Image src={lightbulb} className='w-full h-auto ' />
        </div>
      </main>
    </>
  )
}
 